# Generated by Django 3.2.9 on 2021-11-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TotalExpense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='desc',
            new_name='description',
        ),
    ]
