# Generated by Django 3.2.9 on 2021-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.TextField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
